# Generated by Django 3.2 on 2021-05-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=100)),
                ('blogauthor', models.CharField(max_length=100)),
                ('blogcontent', models.TextField()),
                ('publishdate', models.DateField()),
                ('blogcategory', models.CharField(max_length=100)),
            ],
        ),
    ]
